// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Title       string
	Version     string
	Description string
	Host        string
	BasePath    string
}{
	Title:       "Gomall API",
	Version:     "1.0",
	Description: "这是一个基于 Gin 框架的电商系统 API 文档",
	Host:        "localhost:8080",
	BasePath:    "/api",
}
